#!/bin/bash

unset DISPLAY
export JAVA_OPTS="-Djava.awt.headless=true -Xms128m -Xmx128m"
export X509_USER_PROXY=~/.grid/grid.proxy
java ${JAVA_OPTS} -cp /usr/local/lib/grisu/grython-binary.jar grisu.Grython $@

